services:
  zookeeper:
    image: zookeeper:3.9.3
    container_name: finflow-reactive-solution-kafka-zookeeper-1
    restart: always
    ports:
      - "2181:2181"
    networks:
      - finflow-network

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: finflow-reactive-solution-kafka-kafka-1
    restart: always
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - finflow-network

  # 🐳 Finflow Reactive Spring Boot App
  finflow-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finflow-app
    restart: always
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - finflow-network
networks:
  finflow-network:
    driver: bridge