CREATE TABLE IF NOT EXISTS account (
  account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_number VARCHAR(64) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS  operation_type (
  operation_type_id INT PRIMARY KEY,
  description VARCHAR(128) NOT NULL
);
CREATE TABLE IF NOT EXISTS  transaction (
  transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL,
  operation_type_id INT NOT NULL,
  amount DECIMAL(19,4) NOT NULL,
  event_date TIMESTAMP NOT NULL,
  CONSTRAINT fk_account FOREIGN KEY (account_id) REFERENCES account(account_id)
);
